### ISSUE TITLE
gbc for linux?

### ISSUE THREAD

**Issue by Yabo** [Microsoft/bond#940]
gbc.exe cannot be exeucted on linux natively. Since our build agent runs on linux, we need a bond compiler  to generate classes files during build. Does gbc has a version for linux?

**Comment by SoyYoRafa** [comment]
It would be really helpful if you could provide gbc linux x86_64 builds. I work in a controlled environment. Without getting into details, it's painful to get gbc inside the organization I belong due to the Haskell package dependencies.

**Comment by brodyberg** [comment]
Inside or outside of Microsoft?

**Comment by SoyYoRafa** [comment]
Outside.

**Comment by chwarr** [comment]
Some things to consider when thinking about producing a pre-compiled gbc for Linux:

1. Which distros & architectures should be targeted?
1. How & where should the code be built and packaged?
    * Think about both distro packages and NuGet packages.
1. Compiled code produced by Microsoft must have a digital signature attesting authorship and integrity if the platform supports it (e.g., Authenticode signatures on the Windows platform). If Microsoft is producing the binaries, how is this signing handled?

**Comment by lalo** [comment]
Another option would be a brew recipe, as a middle point. Alas, don't know if this would be useful for people or not.

http://linuxbrew.sh and https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by jasonzio** [comment]
Microsoft has public-facing package repos for .deb and .rpm packages which support the requisite signing.

**Comment by Costo** [comment]
In case that could be useful to anyone:

## How to use the Bond compiler (gbc) in Azure Pipelines with Ubuntu build agents

### 1. Create a Dockerfile to build Bond
 
```docker
# Use the same version of Ubuntu as the build agent.
FROM ubuntu:20.04 as gbc

# Prevent tzdata from hanging the build
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
        curl \
        git \
        clang \
        cmake \
        zlib1g-dev \
        libboost-dev \
        libboost-thread-dev

# Use clang instead of gcc
RUN update-alternatives --set cc /usr/bin/clang

# Install the Haskell Tool Stack
RUN curl -sSL https://get.haskellstack.org/ | sh

RUN git clone --recursive https://github.com/microsoft/bond.git

WORKDIR /bond/build
RUN git checkout tags/10.0.0
RUN cmake -DBOND_ENABLE_GRPC=FALSE .. && make && make install
```

### 2. Run the build

```ps
PS> docker build -t bond -f .\Dockerfile .
```
The build takes about 10 minutes.
After the build (hopefully) succeeds, extract the `gbc` executable.

```ps
PS> docker create --name bond bond
PS> mkdir bond
PS> docker cp bond:/bond/build/compiler/build/gbc/gbc ./bond/gbc
PS> docker rm bond
```

### 3. Upload `gbc` to Azure Artifacts with Azure CLI

```ps
PS> az artifacts universal publish `
    --organization <organisation> 
    --scope project --project <project> `
    --feed <feed> `
    --name bond --version 10.0.0 `
    --description "gbc, the Bond compiler/codegen tool" `
    --path ./bond
```

### 4. Download and use `gbc` in Azure Pipelines

```yaml
- task: UniversalPackages@0
    displayName: 'Download Bond compiler'
    inputs:
        command: download
        vstsFeed: '<project>/<feed>'
        vstsFeedPackage: 'bond'
        vstsPackageVersion: '10.0.0'
        downloadDirectory: '$(Build.SourcesDirectory)/bond'

- task: CmdLine@2
    displayName: 'Update file permissions on Bond compiler'
    inputs:
        script: 'chmod +x $(Build.SourcesDirectory)/bond/gbc'

- task: DotNetCoreCLI@2
    displayName: Build
    inputs:
        command: build
        arguments: '-p:BOND_COMPILER_PATH=$(Build.SourcesDirectory)/bond'
```
